version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
    - "ckleemann"
  allow:
    - dependency-type: all
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
    - "ckleemann"
  allow:
  - dependency-type: all
