name: ci

on: [push, pull_request]


jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Container
        run: |
          docker build -t test-build .

      - name: Run Container
        run: |
          docker run test-build --version | grep pyup
